theme: jekyll-theme-minimal

name: "Emerging_Technology_Atlas"
description: "Welcome to the Emerging Technology Atlas. A collected repository of federal use cases, ideas, and concepts for Artificial Intelligence, Blockchain, Virtual/Augmented Reality, and Social Technologies."
baseurl: /EmergingTechnologyAtlas

# GitHub information
org_name: ctjacks5
repo_name: EmergingTechnologyAtlas
branch: master

# Google Analytics
google_analytics: UA-110413123-1

