# Site metadata
name: "Emerging Technology Atlas"
description: "Emerging Technology Atlas."
baseurl: /EmergingTechnologyAtlas

# GitHub information
org_name: ctjacks5
repo_name: Emerging Technology Atlas
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: "Emerging Technology Atlas"
  url: /Atlashome/
- text: "Section 1. Artificial Intelligence"
  url: /artificialintelligence/

- text: "Section 2: <span>Blockchain</span>"
  url: /blockchain/

- text: "Section 3: <span>Virtual and Augmented Reality</span>"
  url: /virtual-reality/
