# markdown
markdown: kramdown
kramdown:


# Site metadata
name: "Emerging Technology Atlas"
description: "Emerging Technology Atlas"
baseurl: /EmergingTechnologyAtlas

# GitHub information
org_name: ctjacks5
repo_name: EmergingTechnologyAtlas
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: "Emerging Technology Atlas"
  url: /Atlashome/
- text: "Section 1. Artificial Intelligence"
  url: /Artificial-Intelligence/

- text: "Section 2: <span>Blockchain</span>"
  url: /Blockchain/

- text: "Section 3: <span>Virtual and Augmented Reality</span>"
  url: /Virtual-Reality/

theme: jekyll-theme-minimal
